apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-{{ .Values.app.version }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-{{ .Values.app.version }}
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-{{ .Values.app.version }}
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80

{{- if .Values.canary.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-{{ .Values.canary.version }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-{{ .Values.canary.version }}
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-{{ .Values.canary.version }}
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
{{- end}}
