apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{.Values.app.name}}.{{.Values.app.namespace}}.{{.Values.app.domain}}
spec:
  host: {{.Values.app.name}}.{{.Values.app.namespace}}.{{.Values.app.domain}}
  subsets:
    - name: {{.Values.app.name}}-{{.Values.app.version}}
      labels:
        app: {{.Values.app.name}}-{{.Values.app.version}}
    {{- if .Values.canary.enabled }}
    - name: {{.Values.app.name}}-{{ .Values.canary.version }}
      labels:
        app: {{.Values.app.name}}-{{ .Values.canary.version }}
    {{- end }}

---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{.Values.app.name}}.{{.Values.app.namespace}}.{{.Values.app.domain}}
spec:
  hosts:
    - {{.Values.app.name}}.{{.Values.app.namespace}}.{{.Values.app.domain}}
  gateways:
    - http-gateway
  http:
    - route:
        - destination:
            host: {{ .Values.app.name }}.{{ .Values.app.namespace }}.{{ .Values.app.domain }}
            subset: {{ .Values.app.name }}-{{ .Values.app.version }}
          weight: {{ if .Values.canary.enabled }}{{ sub 100 .Values.canary.weight }}{{- else }}100{{- end }}
        {{- if .Values.canary.enabled }}
        - destination:
            host: {{ .Values.app.name }}.{{ .Values.app.namespace }}.{{ .Values.app.domain }}
            subset: {{ .Values.app.name }}-{{ .Values.canary.version }}
          weight: {{ .Values.canary.weight }}
        {{- end }}
