apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-v3
spec:
  selector:
    matchLabels:
      app: hello-v3
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-v3
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-v3
  labels:
    app: hello-v3
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-v2
spec:
  selector:
    matchLabels:
      app: hello-v2
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-v2
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-v2
  labels:
    app: hello-v2
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: nginx
