apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: http-gateway
  namespace: default
spec:
  selector:
    istio: ingress-public
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{- if .Values.gateway.hosts }}
        {{- range .Values.gateway.hosts }}
        - "{{ . }}"
        {{- end }}
        {{- else }}
        - "*"
        {{- end }}
